Feature swerve drive
Decatur-High-GlobalDynamics/FRC-2023-Team-4026 pull request #17
Opened 2023-08-25 00:52 UTC by nubmonkey

I finished changing the code to support NEOs for the steering motor for each module. I commented how stuff works for the subsystem, teleop swerve command, and not much else. The important class central to it is SwerveModule, which I did not comment. Please review this, and tell me why I'm bad at clean formatting. The goal is to have all of you know how it works, so ask questions if need be.

2023-08-25 00:55 UTC, renatodellosso commented
I'll try to get an initial review done by tomorrow night.

2023-08-25 21:51 UTC, renatodellosso commented on src/main/java/frc/lib/math/Conversions.java
This seems to be unmodified from 364's code.

2023-08-25 21:53 UTC, renatodellosso commented on src/main/java/frc/lib/util/CANCoderUtil.java
This seems to be unmodified from 364's code. My understanding of this code is that reduces the polling rate for CANCoders to increase performance.

2023-08-25 21:54 UTC, renatodellosso commented on src/main/java/frc/lib/util/CANSparkMaxUtil.java
Seems to be unchanged from 364. I believe this just sets the polling rate for the motor.

2023-08-25 21:56 UTC, renatodellosso commented on src/main/java/frc/lib/util/COTSFalconSwerveConstants.java
Seems to be unchanged from 364. Just sets up constants. I don't know what most of the constants do though (as of reading this file).

2023-08-25 21:58 UTC, renatodellosso commented on src/main/java/frc/lib/util/CTREModuleState.java
Seems to be unchanged. **I don't see any reason this can't be marked static**, since it contains only static members.

2023-08-25 21:59 UTC, renatodellosso commented on src/main/java/frc/lib/util/CTREModuleState.java
Also I'm uncertain what this code actually does.

2023-08-25 21:59 UTC, renatodellosso commented on src/main/java/frc/lib/util/SwerveModuleConstants.java
Just sets up constants.

2023-08-25 22:00 UTC, renatodellosso commented on src/main/java/frc/robot/CTREConfigs.java
Just inits configs for various motors.

2023-08-25 22:01 UTC, renatodellosso commented on src/main/java/frc/robot/Constants.java
Adds a bunch of swerve config stuff. Also might've readded some old constants.

2023-08-25 22:03 UTC, renatodellosso commented on src/main/java/frc/robot/Ports.java
Just adds the NavX port.

2023-08-25 22:05 UTC, renatodellosso commented on src/main/java/frc/robot/Robot.java
Comments out old tank drive initialization. Adds CTREConfig initialization.

2023-08-25 22:06 UTC, renatodellosso commented on src/main/java/frc/robot/RobotContainer.java
Inits swerve subsystem. Sets up joystick inputs. A bunch of the autos got changed, but we'll probably have to redo auto anyways. The auto code is messy now that I'm looking at it.

2023-08-25 22:09 UTC, renatodellosso commented on src/main/java/frc/robot/commands/VisionCommand.java
Edits vision to use swerve

2023-08-25 22:11 UTC, renatodellosso commented on vendordeps/Phoenix.json
Updates Phoenix library

2023-08-25 22:13 UTC, renatodellosso approved these changes
Looks great! Good work.

A couple notes:
- We'll need to ensure the built-in Shuffleboard logging meshes with our existing logging
- We'll have to redo autonomous
- I believe CTREModuleState can be marked as static

2023-08-29 19:49 UTC, theogillespie commented on src/main/java/frc/lib/util/CANCoderUtil.java
Im not entirely sure what the benefit of reducing the poll rate of the encoders are (larger sample == perhaps less noise), but figure out what the advantage is and document it (so we know what to appropriately use and when

2023-08-29 20:05 UTC, theogillespie requested changes
Looks Good

2023-08-29 20:05 UTC, theogillespie commented on src/main/java/frc/robot/commands/VisionCommand.java
We should make a grandfather swerve class that everything else can inherit- therefore we don't need to do this

2023-08-30 01:08 UTC, Beckoe commented on src/main/java/frc/lib/util/COTSFalconSwerveConstants.java
We only need things for SDSMK4i.

2023-08-30 01:13 UTC, Beckoe commented on src/main/java/frc/robot/Ports.java
Where did you get NavX documentation? I remember having problems with it last year when we considered using it.

2023-08-30 01:17 UTC, Beckoe commented on src/main/java/frc/robot/RobotContainer.java
Yeah, autos will need to be redone with swerve. We probably want to add back stuff like TurnDegrees, DriveDistance, and DriveStraight (or maybe make something like DriveAngle for swerve).

2023-08-30 01:28 UTC, Beckoe commented on src/main/java/frc/robot/RobotContainer.java
Wait sorry, I just saw the new DriveDistanceAuto thing. I assume we can use that.

2023-08-30 01:32 UTC, Beckoe commented on vendordeps/Phoenix.json
This is unrelated to swerve right?

2023-08-30 01:33 UTC, renatodellosso commented on vendordeps/Phoenix.json
I believe so, but we should do it anyways

2023-08-30 01:35 UTC, Beckoe commented
Looks good.

2023-08-30 01:36 UTC, Beckoe approved these changes
Looks good.

2023-08-30 01:58 UTC, nubmonkey commented on src/main/java/frc/robot/Ports.java
we don't have confirmed or tested navx code yet, but I included it as a reminder

2023-09-11 23:14 UTC, renatodellosso commented
Everything that needs testing (from Lyndon):

> We need to use a combination of sysid and regular testing
> 
> We need to test/get the following constants:
> - Module-specific ports 
> - angleOffsets (read 364 documentation for how)
> - Angle motor PID values
> - Drive motor PID vlaues
> - maxSpeed/maxAngular Velocity
> - Drive characterization values (sysid)
> 
> After getting constants and fully testing swerve as a pancake, we will uncomment the following:
> - subsystem inits in RobotContainer
> - subsystem test stuff in Robot.java
> - ALL secondary button mappings
> - autos(will need to be revised fully anyway) and auto selection
> - auto logging

2023-10-17 20:07 UTC, merged